fix: open mail
JongHyeok-Park/FAQ_CHAT_Front pull request #42
Opened 2024-05-03 15:55 UTC by thanhhien234

2024-05-03 17:46 UTC, JongHyeok-Park requested changes

2024-05-03 17:46 UTC, JongHyeok-Park commented on pages/index.html
> +    <meta name="viewport" content="width=d evice-width, initial-scale=1">
오타

2024-05-03 17:46 UTC, JongHyeok-Park commented on pages/login.html
>    });
이거 이벤트 리스너 없이 적으면 되는데..?

2024-05-03 17:46 UTC, JongHyeok-Park commented on pages/login.html
>    });
제가 자세히 안 봣네여..; 쏘리 이거 eventListener는 없애고 안에 내용 밖으로 빼주세요.

2024-05-03 17:47 UTC, thanhhien234 commented on pages/login.html
>    });
아 맞네요

2024-05-04 05:47 UTC, JongHyeok-Park approved these changes

2024-05-04 05:49 UTC, merged